### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [Marcello09/MultiArduinoDrone#2]
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by Marcello09** [comment]
You are right, thanks for pointing that out for me, will fix that

**Comment by Marcello09** [comment]
Fixed in setup.ino, will fix in others as well, thankyou
